spring.application.name=Pokemon-team-builder

pokeapi.baseurl=https://pokeapi.co/api/v2

# Configuración de la Base de Datos PostgreSQL con Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon
spring.datasource.username=admin
spring.datasource.password=culoconcaca
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
# Opciones comunes: update (actualiza el esquema), create (crea y destruye al cerrar), validate (solo valida). Usa 'update' para desarrollo.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Propiedad opcional para un mejor manejo de errores en caso de problemas con la conexión
spring.datasource.testOnBorrow=true
